skill_classification/skill_app/urls.py
from  django.urls import path
from . import views
app_name = "predict"

urlpatterns = [
    path('', views.predict, name='prediction_page'),
    path('predict/', views.predict_chances, name='submit_prediction'),
    path('results/', views.view_results, name='results'),
]

skill_classification/skill_classification/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('skill_app.urls')),
    path('admin/', admin.site.urls),
]

skill_classification/skill_app/models.py
from django.db import models

# Create your models here.
class PredResults(models.Model):

    skill=models.TextField()
    classification = models.CharField(max_length=100)

    def __str__(self):
        return self.classification

skill_classification/skill_app/views.py
from django.shortcuts import render
from django.http import JsonResponse
import pandas as pd
from .models import PredResults
import pickle


# Create your views here.


def predict(request):
    return render(request,'predict.html')


def predict_chances(request):

    if request.method=="POST":

        # Receive data from client
        skills = request.POST["skills"]
        print(skills)
        
        # Unpickle model
        model = pickle.load(open("E:/Advanced Data Science and Machine Learning/AI/NLP/Projects/Skill/skill_classification-20220712T151931Z-001/skill_classification/skill_app/skill.sav", "rb"))
        
        # Make prediction
        result = model.predict([skills])
        print(result)
        skill = skills
        classification = result

        obj=PredResults.objects.create(skill = skills,classification = result)
        obj.save()
        print(result)
        #print(skills)
        
        return render(request,'predict.html',{'result': classification,'skills':skills },)
                            



def view_results(request):
    # Submit prediction and show all
    data = {"dataset": PredResults.objects.all()}
    return render(request, "results.html", data)      

skill_classification/templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Iris prediction</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">DB</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

skill_classification/templates/predict.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>Skills <span id="skills"></span></div>
                
                <h5 class="pt-3">Prediction Classification:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Skill_ Classification</h1>

            <form action="{% url "predict:submit_prediction" %}" id="post-form" method="POST">
                {% csrf_token %}               
                <div class="form-group">
                    <label for="Skills">Skills</label>
                    <input type="text"  class="form-control"   name='skills' placeholder="" required>
                </div>
                
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<!-- <script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                skills:$('#skills').val(),
                
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'POST'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("skills").innerHTML = json['skills']
                
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script> -->

{% endblock %}

skill_classification/templates/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Prediction Results</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">skills</th>
                
                <th scope="col">Prediction</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.skill}}</td>
                    
                    <td>{{ data.classification }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}